-- MySQL Script generated by MySQL Workbench
-- Mon May 13 14:19:31 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema imdab_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema imdab_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `imdab_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `imdab_db` ;

-- -----------------------------------------------------
-- Table `imdab_db`.`game`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdab_db`.`game` (
  `ID` INT(10) UNSIGNED NOT NULL,
  `Rating` TINYINT(3) NULL DEFAULT '-1',
  `NrOfVotes` INT(10) NULL DEFAULT '-1',
  `Title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imdab_db`.`game_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdab_db`.`game_category` (
  `GameID` INT(10) UNSIGNED NOT NULL,
  `Category` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GameID`, `Category`),
  CONSTRAINT `fk_game_category_game1`
    FOREIGN KEY (`GameID`)
    REFERENCES `imdab_db`.`game` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imdab_db`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdab_db`.`user` (
  `ID` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `imdab_db`.`review`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `imdab_db`.`review` (
  `user` INT(10) UNSIGNED NOT NULL,
  `game` INT(10) UNSIGNED NOT NULL,
  `rating` TINYINT(4) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `helpfullnessPositive` INT(11) NULL DEFAULT NULL,
  `helpfullnessNegative` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`user`, `game`),
  INDEX `fk_review_game1_idx` (`game` ASC),
  CONSTRAINT `fk_review_user`
    FOREIGN KEY (`user`)
    REFERENCES `imdab_db`.`user` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_review_game1`
    FOREIGN KEY (`game`)
    REFERENCES `imdab_db`.`game` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
